### ISSUE TITLE
multiple MBE buffers

### ISSUE THREAD

**Issue by JDeuce** [fholgado/minibufexpl.vim#37] opened 2012-02-01 15:29 UTC
Hey 

I'm using your version of MBE, it works pretty good but once in awhile it ends up messing up and opening multiple instances of the MBE buffer (as pictured in my screenshot below):

![Screenshot](http://i.imgur.com/vf28w.png)

This same thing was happening with the old vimscripts version, and it's happened to me across multiple machines, so I'm sure I'm doing something wrong on some level, but I'm not sure what or why it would open multiple buffers, got any tips?

**Comment by sillykelvin** [comment] 2012-02-24 06:24
Yes, I have this issue too. If I have opened two buffers, and if I type ":e ." to open the third file, then it will generate a new MBE window. any ideas about this issue? Thanks.

**Comment by JDeuce** [comment] 2012-02-28 15:01
I tried what you said and I was unable to reproduce the issue by having 2 open buffers and doing ":e .".
This might be related to #31, but I was also unable to reproduce using his method.

I haven't yet figured out a way that I can consistently make it happen (which I know would make it much easier for fholgado to fix).

One thing I will add is that when it does happen, there seems to be some sort of corrupt state in MBE, because the script will keep opening multiple buffers. 

For example if I \mbc them all and open a new buffer, then MBE comes back as normal (I have g:miniBufExplorerMoreThanOne as default). However when I use MBE to switch to the next buffer then it causes a second MBE window to pop up (and then a third.. and then a fourth, etc).

**Comment by sillykelvin** [comment] 2012-03-01 16:29
this is really strange, I only can reproduce by opening specific files, others will not. I don't know if this is caused by incompatible plugins, I also have NERDTree, FuzzyFinder, NeoComplCache installed.

I checked issue #31, my problem is similar to his.

**Comment by wolfgangpfnuer** [comment] 2012-03-08 12:21
i got the same problem, i have the feeling it is somewhat related with the following things (i.e. they increase the likelyhood of the bug appearing)

A) switch current folder with NerdTree (for example by using bookmarks) and open a file
B) jump to other files using ctags, open NerdTree there as well to edit a file from same folder
C) double-click on a file in MiniBufExpl

It really seems to be a duplicate (or very close sibling) of #31

**Comment by JDeuce** [comment] 2012-03-09 19:14
I also have NERDTree installed, no fuzzyfinder, neocomplcache.

**Comment by juanolon** [comment] 2012-05-16 22:08
I also have this issue, really strange. this happens specially when i switch between buffers with <C-TAB> and <C-S-TAB> really annoying..

**Comment by melta** [comment] 2012-05-21 12:36
I also have this issue, no NERDTree and no fuzzyfinder installed.

**Comment by sharonjl** [comment] 2012-06-04 01:04
I am seeing this issue as well. Even on a clean install. I have NERDTree installed; but no fuzzy or neocomplcache.

**Comment by weynhamz** [comment] 2012-11-20 02:12
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

I believe this issue has been fixed in my [develop branch](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) after some refactorings, please give it a try and let me know if it works.

**Comment by weynhamz** [comment] 2012-11-23 22:51
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.

**Closed as completed by weynhamz** 2012-11-23 22:51 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2013-05-10 18:29
Duplicate of #31
