### ISSUE TITLE
minibufexpl window always mark self as last active

### ISSUE THREAD

**Issue by gorkunov** [fholgado/minibufexpl.vim#7] opened 2011-03-22 12:19 UTC
I'm using minibufexpl and  nerdree. So when i try to open any file from nerdtree as vsplit in current buffer then it split minibufexplorer window not current editor window. It happens because nerdree split last active window but after i switch from editor window to nerdtree minibuferexpl get focus (a little time) for change colors for current active 'tab' so minibufexpl window became last active window.
Maybe vim has some options to switch 'last active window' marker from minibufexpl  window to previous active window?

**Comment by fholgado** [comment] 2011-04-03 21:56
Hi goruknov. I'm looking into this to see how it can be fixed. Can you test with the MBE version found here to see if the problem persists? If so, I'll have to see what could be causing this problem:

http://www.vim.org/scripts/script.php?script_id=159

Thanks again for the report. I hope to get this fixed too since I'm also a NERDTree user.

**Comment by gorkunov** [comment] 2011-04-05 12:30
I installed last version from http://www.vim.org/scripts/script.php?script_id=159 and it works correct (open split in last edited window).

thanks!

**Comment by fholgado** [comment] 2011-04-17 14:03
Thanks for confirming that. I will be comparing the two versions to see what's causing this issue. I think this issue might be what was causing the compatibility issues with FuzzyFinder... I hope to get it tracked down and fixed soon!

**Comment by folke** [comment] 2011-11-15 11:18
This patch most likely fixes this: https://github.com/fholgado/minibufexpl.vim/pull/30

**Comment by chrisnicola** [comment] 2012-04-10 22:07
Not fixed from what I can see. Still have this problem with NERDTree.

**Comment by weynhamz** [comment] 2012-11-20 01:49
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

 I believe that techlivezheng/vim-plugin-minibufexpl@3add236 and techlivezheng/vim-plugin-minibufexpl@4155048 should fix this issue now. 

Please give it a try and let me know if it works.

**Comment by weynhamz** [comment] 2012-11-23 22:53
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.

**Closed as completed by weynhamz** 2012-11-23 22:53 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2013-05-10 17:58
Duplicate of #3
