### ISSUE TITLE
Duplicate MBE opens after I :cd and move to a new buffer

### ISSUE THREAD

**Issue by singerb** [fholgado/minibufexpl.vim#83] opened 2013-04-22 18:35 UTC
I've started using a gvim that I just keep open, and `:cd` around when I want to work somewhere else (so my ack, command-t etc work nicely). What I've noticed though, is that when I do that, as soon as I switch to another buffer/window after I `:cd` MBE will open another, identical MBE window. I can close it with no apparent ill effects, and once I move back to another window the one I left behind resizes itself to the right size, but it's somewhat annoying.

**Comment by dtsteinm** [comment] 2013-04-22 19:13
@singerb I believe I've seen the same issue. In my case, moving MBE closer to the top of my list of Vundle bundles in my .vimrc file seems to have corrected the problem.

**Comment by singerb** [comment] 2013-04-22 19:15
Hmm. I'm using pathogen, not Vundle, so I don't believe I have control over loading order, but I can try playing games with filenames.

**Comment by dtsteinm** [comment] 2013-04-22 20:06
That could be time consuming. If you haven't already figured it out, it might help to compare bundles. I'm not using either Command-T or Ack, but maybe there is some other commonality?

I'm currently using: Syntastic, vim-colors-solarized, minibufexpl.vim, vim-surround, vim-fugitive, vim-git, supertab, gundo.vim, vim-makegreen, L9, FuzzyFinder, pep8, TaskList.vim, The-NERD-Commenter and jedi-vim.

**Comment by singerb** [comment] 2013-04-23 00:47
So we certainly have some overlap. I've got:

Command-T, ack.vim, camelcasemotion, eclim, gundo.vim, minibufexpl.vim, supertab, syntastic, tagbar, vim-colors-solarized, vim-commentary, vim-lawrencium

And a few other syntax/indent/ftdetect files for various file types (fish, markdown, scala, lilypond).

**Comment by dtsteinm** [comment] 2013-04-23 01:31
Seems to be easiest for me to reproduce the issue, without rearranging bundle order (so where it's loaded doesn't seem to matter greatly), by going to a different buffer inside the MBE window, and once a duplicate appears, it continues to do so when navigating buffers. It seemed to happen more often after having the same Vim session open for more than ~2 hours or with a gundo window open, but can't confirm that with certainty.

**Comment by weynhamz** [comment] 2013-04-23 01:45
Hey, just try develop branch, should be fixed there.

**Comment by weynhamz** [comment] 2013-05-08 13:48
Hey, any update? Does the develop branch solve this issue?

**Comment by dtsteinm** [comment] 2013-05-08 22:08
It does appear to be slightly more stable, wrt this issue, than the master branch.

**Comment by singerb** [comment] 2013-05-08 22:44
Yes, I agree that it seems to be better on the development branch.

**Comment by weynhamz** [comment] 2013-05-09 02:01
Okay, I am closing this issue, feel free to reopen it if it still hurts.

**Closed as completed by weynhamz** 2013-05-09 02:01 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2013-05-11 04:00
Duplicate of #31
