### ISSUE TITLE
Slows down significantly when opening 10+ buffers

### ISSUE THREAD

**Issue by brendonrapp** [fholgado/minibufexpl.vim#6] opened 2011-02-18 21:47 UTC
I've noticed on my machines that when open buffers starts to approach and exceed double digits, performance is significantly impaired. Opening and switching buffers goes from instantaneous to delayed, and even editing a buffer can become plagued with pauses and hiccups.

When I remove minibufexpl from my Vim plugins and replace it with BufExplorer, the issue disappears (at least up to the number of open buffers I've tried, 25 or so). Buffer opening, switching, and editing remains instantly responsive.

I've experienced this behavior in two different settings: in MacVim on a MacBook Pro, and in Gvim in Ubuntu on an AMD quad-core. Each machine flush with free memory.

I have not yet experimented with a bare Vim profile, so I can't yet rule out some sort of interfering side-effect of another plugin. I will try that next.

**Comment by fholgado** [comment] 2011-02-22 02:16
Hey there,

Thank you for the report. I think you are right in terms of MBE slowing down with multiple files. The method that handles updating the explorer when a file changes loops through every file, so it's understandable that it will slow down.

I do have plans to optimize MBE, I just finished with hockey for the year and I will have some free time to put into MBE these coming weeks. I will keep you posted on the results, and feel free to tell me any suggestions etc.

Thanks!

**Comment by binduwavell** [comment] 2011-02-22 06:09
For what it's worth I just opened 50 files using command line vim on my old 2008 MacBook Pro. Was very fast to switch buffers and open new buffers. Also tried latest release build of MacVim. Also very fast. I'm guessing there is some interaction going on. I'm using the version of MBE from sourceforge.

**Comment by brendonrapp** [comment] 2011-02-22 06:55
I will definitely need to experiment to try and pin down the potential interaction.

Question: as you opened more and more buffers, was there any perceptible performance degradation? In other words, by "very fast", do you mean "near-instant", or are you perhaps working with a more tolerant definition of "fast" than I might be? I'm assuming it's the former, but just making sure. I could imagine a more patient person than I considering a half-second delay as still being "fast". :)

Anyway, hopefully I can find some time soon to poke around with it a bit and perhaps be able to provide some more useful detail to work from.

**Comment by fholgado** [comment] 2011-02-24 20:58
Hi guys,

I can confirm that opening ~60 files does slow down switching buffers in Vim considerably.

I am almost positive that the logic that the latest version of MBE uses is not as efficient as it should be. Because of all the patches that Oliver and others have sent me, I think some things are not implemented properly.

My plan is to revert back to the latest original verision of MBE that Bindu wrote and re-integrate the new code and additions into that. This way, I can start checking for bugs periodically and hopefully squash most of the things that are currently open.

I am working on a student's schedule so I am going to do my best. My schedule's been somewhat upside down since I had to take my computer in for repairs all last week.

Thanks for your patience!
Federico

**Comment by mblondel** [comment] 2011-04-07 02:34
I have the same sluggishness issue starting from around 10 buffers. With the latest release from http://www.vim.org/scripts/script.php?script_id=159, the problem disappear.

**Comment by andrew-hill** [comment] 2011-04-13 02:01
I've seen this sluggishness from about 6 files on a current model MacBookPro with MBE 6.4.1b2. One possible thing to note is my MBE line was quite long as all the files had long names and were in different directories, so it was spanning a couple of lines...

**Comment by whitelynx** [comment] 2011-05-20 03:51
I hadn't noticed this issue, so I opened another (#13) where I tracked down the speed issues to between commits c874c3f22fb953b988a89af854e4c9ee0cd35f94 (fast) and be428a722760ab2439b56be4b10d8c3a67869673 (slow). It does seem that this corresponds with the introduction of the duplicate buffer name checking code as suggested by fholgado, so I'm pretty sure we've determined the cause of the slowness. For now, I'm just using an older release on MBE (version 6.3.7) but I may try to take a look at the duplicate check code and see if I can make any suggestions on improving it.

**Comment by fholgado** [comment] 2011-05-20 03:59
That sounds awesome. In the meantime, I am about to push a build that allows you to turn off the duplicate buffer name checking for users that have a lot of open buffers simultaneously. It's just a temporary fix until we can optimize the process :)

By all means, I would love some suggestions on how to speed up the code. I'll open up discussion on it when I start working on the issue. It's just a matter of performing the checking only when needed instead of doing it every time a buffer is switched. This should only slow down file opening temporarily, but not buffer switching.

**Comment by fholgado** [comment] 2011-05-20 04:40
As I mentioned, here is an updated build that allows you to turn off the duplicate buffer name checking feature:

https://github.com/fholgado/minibufexpl.vim/blob/development/plugin/minibufexpl.vim

You can use it by adding the following to your .vimrc:

```let g:miniBufExplCheckDupeBufs = 0

```

I will get working on optimizing this process soon!

```

**Comment by jmnas** [comment] 2011-05-26 23:44
I took a crack at making the duplicate name checking faster [here](https://github.com/jmnas/minibufexpl.vim/commit/a8399d4bacd71e4e2779c480091eca4627f2ea1a). Performance is better mostly because it only happens when a buffer is opened, but I also reworked the checking so opening files isn't as slow. Only lightly tested.

**Comment by fholgado** [comment] 2011-05-27 16:37
Sweet! Taking a look at it now, I'll report what I find. Thanks again :)

**Comment by jmnas** [comment] 2011-05-27 19:39
Ok, to be clear, it isn't a complete solution that could be rolled into a release. It was more of an experiment to see if it could be faster. One issue is that when buffers are deleted it probably needs to do some cleanup.

**Comment by dkinzer** [comment] 2012-01-05 14:32
I can confirm this too.And in my case it happens around six or seven opened buffers.  It happens very quickly when I do a vimgrep and copen a list with many hits.

**Comment by fholgado** [comment] 2012-02-27 03:26
@jmnas It would be great if you could make a pull request with your changes so that we can test. I still have this feature turned off until we can speed it up a bit. Thanks :)

**Comment by anttihirvonen** [comment] 2012-09-15 14:42
+1

I would really like to see this being solved. I always have to turn the duplicate checking off when developing Django projects, as many of the files have the same names (views.py/models.py/etc. in every app). This makes minibufexpl very slow. 

Maybe someone with VIM scripting experience could take a look at the improvements made my @jmnas?

**Comment by dezza** [comment] 2012-11-09 12:10
fholgado: Thanks for the tip, setting that single variable will let me open 140 buffers in a single vim on Windows in a jiffy !

**Comment by weynhamz** [comment] 2012-11-20 01:13
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

The mechanism of checking buffers with duplicate name has been totally refactored(Thanks to @jmnas for the orginal work.), I believe that techlivezheng/vim-plugin-minibufexpl@5715dd9, techlivezheng/vim-plugin-minibufexpl@f3723aa, techlivezheng/vim-plugin-minibufexpl@950a81a and techlivezheng/vim-plugin-minibufexpl@763a623 should fix this issue now. Unique name generation has also been refactored, the string shown in MBE should uniquely identified the buffer now.

Please give it a try and let me know if it works.

**Comment by justinmk** [comment] 2012-11-20 03:14
@techlivezheng, thanks for notifying about your improvements. It works well so far.

**Comment by weynhamz** [comment] 2012-11-23 22:50
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.

**Closed as completed** 2012-11-23 22:55 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2013-05-11 10:02
Related to #5
