### ISSUE TITLE
two files same name

### ISSUE THREAD

**Issue by pixelmuerto** [fholgado/minibufexpl.vim#5] opened 2011-01-22 23:39 UTC
when I try open two differents files with same name in differents paths  
vim fileName ../fileName -o  
I get this error  

Error detected while processing function     <SNR>11_AutoUpdate..<SNR>11_StartExplorer..<SNR>11_DisplayBuffers..<SNR>11_ShowBuffers..<SNR>11_B
uildBufferList..CheckRootDirForDupes:
line    3:
E684: list index out of range: -1
E15: Invalid expression: (a:path1[a:level] == a:path2[a:level])

**Comment by fholgado** [comment] 2011-01-23 03:53
Hey there, can you tell me what OS/platform you are using Vim on? The code that compares the filenames tries to take into account Windows filepaths, but since I don't have a windoze computer, I haven't been able to test it.

Let me know and we'll go from there!

**Comment by pixelmuerto** [comment] 2011-01-23 15:49
I use vim in OSX 10.6.6

**Comment by andrew-hill** [comment] 2011-01-27 00:33
I get the same problem (MacVim 7.3 on OS X 10.6.6)

**Comment by fholgado** [comment] 2011-01-27 14:42
Hi guys, sorry for the delay! Are you both opening files from the command line? Please let me know if you can reproduce this opening files in any other way (such as dragging into the icon, from the open menu, Vim command line, etc.)

I usually use PeepOpen/NerdTree to open files and it seems to work fine, although Vim is never opening 2 files at the same exact time. I think that is the issue.

I need to add some error checking to that function and that should hopefully fix it. I will be working on MBE over the weekend, so expect a fix coming soon!

**Comment by andrew-hill** [comment] 2011-01-28 00:20
It's not that they're "opened" at the same time, it's that they're "open" at the same time... it's not about the timing of the opening, just that they are both open in different buffers in the same MacVim tab.

e.g. Open ~/Code/ProjectA/CMakeLists.txt in MacVim
make some changes... whatever
open ~/Code/ProjectB/CMakeLists.txt in another buffer, same window/tab
you may have to switch between them to start getting errors (i can't remember exactly, I've reverted to an older version of MBE temporarily because of this bug and issue 3 getting in the way of work, but can do some more rigorous testing if you can't reproduce)

**Comment by pixelmuerto** [comment] 2011-01-28 13:36
I open the file this way 
vim -o ~/path1/file ~/path2/file
or -O or -p or from inside of vim 
:sp ~/path1/file 
:sp ~/path2/file 
in any case I get  same error

**Comment by pixelmuerto** [comment] 2011-01-28 13:43
// sorry, I accidentally close the issue, how reopen ?

**Comment by fholgado** [comment] 2011-01-30 20:18
Hi guys.

Please take a look at the new beta release here:

https://github.com/fholgado/minibufexpl.vim/commits/6.4.1b2

It should fix all the issues mentioned above. Please give it a run and let me know if the problems are fixed. Once you guys confirm, I will close out the issue.

Thanks again for the bug reports. I appreciate you guys taking the time to submit them  :)

**Comment by pixelmuerto** [comment] 2011-01-30 21:50
ok, everything working fine.
I test with  
vim path1/file path2/file -o  
vim path1/file path2/file -O  
vim path1/file path2/file -p  

and from inside of vim  
:sp 
:tabnew 

thanks for the plugin :D

**Comment by andrew-hill** [comment] 2011-02-01 01:07
6.4.1b2 seems to have fixed this bug for me as well, thanks

**Comment by fholgado** [comment] 2011-02-01 01:08
Awesome. Thanks for getting back to me. I'll go ahead and close this one out. On to the others!

**Closed as completed by fholgado** 2011-02-01 01:08 UTC
Labels: bug

**Comment by weynhamz** [comment] 2012-11-20 01:30
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

The mechanism of checking buffers with duplicate name has been totally refactored(Thanks to @jmnas for the orginal work.), I believe that techlivezheng/vim-plugin-minibufexpl@5715dd9, techlivezheng/vim-plugin-minibufexpl@f3723aa, techlivezheng/vim-plugin-minibufexpl@950a81a and techlivezheng/vim-plugin-minibufexpl@763a623 should fix this issue now. Unique name generation has also been refactored, the string shown in MBE should uniquely identified the buffer now.

Please give it a try and let me know if it works.
