### ISSUE TITLE
Vim slowed down by MBE.

### ISSUE THREAD

**Issue by egery** [fholgado/minibufexpl.vim#61] opened 2012-08-14 10:36 UTC
Hello,

Your mbe brings neat ideas, but lower Vim's responsiveness to an unacceptable level.
I've tested with a plain Vim version 7.3.353 without any plugins / .vimrc (except pathogen).

Without mbe, if I open 20 moderately sized files (~6000 char), every buffer switch (`:bn`) is instantaneous.
With mbe, it takes uncomfortable fractions of second.
I've experienced delay of 2 seconds, but in conjunction with other plugins.

I've no idea how I can investigate this issue.

Regards,
Yves.

**Comment by lewurm** [comment] 2012-08-27 12:24
I can confirm that. I updated MBE from a quite old version recently and I have the same experience as egery.

**Comment by lewurm** [comment] 2012-08-27 14:14
I did a `git bisect` session, here's the result:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
08f219db9aa17d49617e1afd88e10f080dd37d98
4be655de9b66515dcca5ac01a40b2130562e4ee6
cb414b25ee013c130a4fcac7097c770ac4605776
be428a722760ab2439b56be4b10d8c3a67869673
We cannot bisect more!
```

with the skipped commits, `vim` throws a lot of error messages on startup and it wasn't useable.

HTH

**Comment by fholgado** [comment] 2012-08-27 14:17
Hi guys,

Sorry for the lack of activity. Please check here for an answer:

https://github.com/fholgado/minibufexpl.vim/blob/master/doc/minibufexpl.txt#L254

## 

Federico

**Comment by lewurm** [comment] 2012-08-27 14:20
awesome, thanks!

**Comment by egery** [comment] 2012-08-27 14:53
Yep, the workaround `let g:miniBufExplCheckDupeBufs = 0` works. Thank you !

**Comment by weynhamz** [comment] 2012-11-20 01:36
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

The mechanism of checking buffers with duplicate name has been totally refactored(Thanks to @jmnas for the orginal work.), I believe that techlivezheng/vim-plugin-minibufexpl@5715dd9, techlivezheng/vim-plugin-minibufexpl@f3723aa, techlivezheng/vim-plugin-minibufexpl@950a81a and techlivezheng/vim-plugin-minibufexpl@763a623 should fix this issue now. Unique name generation has also been refactored, the string shown in MBE should uniquely identified the buffer now.

Please give it a try and let me know if it works.

**Comment by weynhamz** [comment] 2012-11-23 22:43
Hey, I am closing this issue, because it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.

**Closed as completed by weynhamz** 2012-11-23 22:43 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2012-11-23 23:15
Related to #5

**Comment by weynhamz** [comment] 2013-05-10 18:32
Duplicate of #6
