### ISSUE TITLE
Performance regression in version 6.4.0

### ISSUE THREAD

**Issue by whitelynx** [fholgado/minibufexpl.vim#13] opened 2011-05-03 15:13 UTC
I usually have quite a large number of tabs open. (the session I'm testing this on has 27 tabs) When I first started trying out this branch of minibufexpl, I noticed that it was incredibly slow when switching tabs; however, the original minibufexpl on the Vim site didn't have this issue. I went back through all of the downloads listed here on github, and found that the regression seems to have occurred between 6.3.7 and 6.4.0.

When I have a decent number of tabs open (I've only been testing with my current session of 27 tabs, but I can try other numbers of tabs if it'd help) I see the following behavior: Using 6.3.7, buffer switches (`:bn` / `:bp`, which I bind to `<C-Tab>` and `<C-S-Tab>` respectively) are fast; the speed is indistinguishable from stock Vim with no minibufexpl-like plugin. Using 6.4.0, it takes more than a full second to switch tabs each time I press `<C-Tab>` or enter `:bn`.

I'll clone the repository and see if I can track down a specific revision that caused this regression.

**Comment by whitelynx** [comment] 2011-05-03 15:52
I've narrowed it down to between commits c874c3f22fb953b988a89af854e4c9ee0cd35f94 (fast) and be428a722760ab2439b56be4b10d8c3a67869673 (slow). I can't get more specific than that because the 3 intervening revisions all generate tons of errors both on load and when switching buffers.

**Comment by fholgado** [comment] 2011-05-20 02:55
Hi there! Please take a look at the discussion on the subject on Issue #6. The issue arises from the duplicate buffer name checking procedure, and I am planning on letting the user choose to turn on/off the feature until it's speedy enough for everyday use.

Let me know what you think! I am closing this issue so that we can continue discussion in it's respective place.

Thanks again,
Federico

**Closed as completed by fholgado** 2011-05-20 02:55 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2012-11-20 01:13
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

The mechanism of checking buffers with duplicate name has been totally refactored(Thanks to @jmnas for the orginal work.), I believe that techlivezheng/vim-plugin-minibufexpl@5715dd9, techlivezheng/vim-plugin-minibufexpl@f3723aa, techlivezheng/vim-plugin-minibufexpl@950a81a and techlivezheng/vim-plugin-minibufexpl@763a623 should fix this issue now. Unique name generation has also been refactored, the string shown in MBE should uniquely identified the buffer now.

Please give it a try and let me know if it works.

**Comment by weynhamz** [comment] 2012-11-23 23:04
Related to #5

**Comment by weynhamz** [comment] 2013-05-10 18:32
Duplicate of #6
