### ISSUE TITLE
Opening files with the same filename causes an error

### ISSUE THREAD

**Issue by john2x** [fholgado/minibufexpl.vim#9] opened 2011-04-15 16:54 UTC
When opening files with the same filename using the `:e` command and one of them is on the same level as the CWD, it causes the error:

```
Error detected while processing function <SNR>17_AutoUpdate..<SNR>17_BuildBufferList..CheckRootDirForDupes:
line    3:
E684: list index out of range: -1
Press ENTER or type command to continue
```

Pressing ENTER just keeps on displaying the same error.

Note: It doesn't come up when opening the files via NERD_Tree plugin. Only when using `:e`. I'm using GVim 7.3 on Windows. Haven't tried on Mac OS X yet.

**Comment by fholgado** [comment] 2011-04-16 14:17
John,

Try the latest build in the development trunk. this issue is fixed there! I'll move the next build to stable soon. 

Thanks!

**Comment by john2x** [comment] 2011-04-17 03:57
Awesome. Thanks!

**Comment by john2x** [comment] 2011-04-19 17:46
Updated to the latest version on Windows, but now the full path is displayed instead of just the filename (regardless of files with the same names are open). The latest version works fine on Mac OS X.

**Comment by fholgado** [comment] 2011-04-21 00:28
Hey there,

I was actually looking for some Windows testers when I was developing the feature but I didn't get any responses. If you would be willing to be my guinea pig, I will send you a development version once I fix the issue to see if it works. 

The problem itself just stems from the different separator character that windows (/) and unix () systems use. I have a mechanism to figure out what system you are on, but something must be missing that's causing it not to work. Let me know if you can help test!

**Comment by john2x** [comment] 2011-04-21 06:56
Sure. Sign me up!

**Comment by xyos** [comment] 2011-04-24 01:22
i will help you if you want too ;)

**Comment by john2x** [comment] 2011-05-02 14:07
Any update for the testing? :)

**Comment by fholgado** [comment] 2011-05-03 00:12
Hi John,

Getting to it this week sometime. I graduate on Sunday, but I promise I'll get to it :)

Whoohoo, no more school!

## 

Federico Holgado
http://fhl.gd

**Comment by john2x** [comment] 2011-05-03 08:11
Haha. That's awesome. Congrats!

**Comment by jmnas** [comment] 2011-05-15 23:11
Regarding the absolute path on windows: note that it doesn't show the absolute path when shellslash is set. I'm using windows but with cygwin as my shell, so setting shellslash generally works better.

**Comment by john2x** [comment] 2011-05-16 13:58
Thanks. Didn't know about `shellslash`. Seems to be working fine now. Does setting `shellslash` have side effects?

**Comment by jmnas** [comment] 2011-05-16 22:39
It affects how the shell expands filenames, e.g., when using :e. Since I'm using cygwin as a shell it makes things work better but I don't know how well it would work with cmd.exe as your shell.

**Comment by sontek** [comment] 2011-05-20 02:13
I have fixed this in my branch https://github.com/sontek/minibufexpl.vim

**Comment by fholgado** [comment] 2011-05-20 02:41
Hi Sontek, I actually read your article on Vim the other day and saw that you had created a branch for MBE. Cool! Did you utilize this same method to fix the issue? I am finally out of school and have some time to get going on MBE stuff. It would be great if you can show me how you've fixed it.

Thanks again!

**Comment by fholgado** [comment] 2011-05-20 04:41
Hi guys,

I have added the shellslash setting to MBE so that you don't have to do it in your .vimrc. Could you please test this build to confirm everything is working? I don't have a Windows computer with Vim to test with, so I am reliant on you guys to tell me of any problems!

https://github.com/fholgado/minibufexpl.vim/blob/development/plugin/minibufexpl.vim

Thanks in advanced!

**Comment by john2x** [comment] 2011-05-20 14:13
Thanks. I'll report back as soon as I tame Cygwin.

**Comment by jmnas** [comment] 2011-05-22 23:51
Your fix works, but I think it would be better not to set shellslash for the user. I looked at your code, and I think you should be setting `s:PathSeparator` based on the OS and the shellslash setting. This would work:

```
if ((has('win32') || has('win64')) && !&shellslash)
    let s:PathSeparator = '\'
endif
```

**Comment by fholgado** [comment] 2011-05-27 16:45
Thanks for the suggestion... Here is the original code:

```
        if (a:delBufNum == l:i)
            " check to see what platform we are in
            if (has('unix'))
                let s:PathSeparator = '/'
                call <SID>DEBUG('separator set to  '.s:PathSeparator,10)
            else
                let s:PathSeparator = '\'
                call <SID>DEBUG('separator set to  '.s:PathSeparator,10)
            endif

            call <SID>DEBUG('Separator is '.s:PathSeparator,10)

            continue
        endif
```

Could you explain what checking for shellslash would do? Would this mean that we should have users set shellslash in their own .vimrc? And if so, why? Thanks so much for your help!

**Comment by jmnas** [comment] 2011-05-27 19:27
You need to figure out what the path separator is so that you can split paths properly. It is '/' on *nix and '\' on windows unless the user has set shellslash.

If you look at what pathogen [does](https://github.com/tpope/vim-pathogen/blob/master/autoload/pathogen.vim#L78) you'll see the separator is `!exists("+shellslash") || &shellslash ? '/' : '\'` which looks pretty good.

In the original code, it looks like you only set s:PathSeparator to '\' if you are deleting a buffer which, unless I'm missing something, is why it didn't work.

I think the easiest fix is to just put `let s:PathSeparator = !exists("+shellslash") || &shellslash ? '/' : '\'` at the top of your script. If you want to avoid the global variable, use a function like pathogen does.

Regarding shellslash, the only reason I know of to set this is if you are using Cygwin as your shell for vim on Windows. The setting doesn't even exist in *nix vim. Since minibufexpl doesn't know whether the user is using Cygwin, it shouldn't be messing with shellslash.

**Comment by Illiux** [comment] 2011-08-01 21:30
I can confirm that setting shellslash indiscriminately on windows breaks things. I encountered problems with it and using netrw SCP on windows. Setting shellslash causes Vim to single-quote the paths, something cmd.exe can't understand.

**Comment by fholgado** [comment] 2011-10-20 23:07
Hi guys,

I've gone ahead and updated the code not to set shellslash indiscriminately. Since I don't have a way (or the will) to test this in Windows, please try this updated script to see if it works OK. If you can confirm, I'll go ahead and merge it into the stable branch.

Link: http://f.fhl.gd/B8or

Thanks in advance :)

**Comment by john2x** [comment] 2011-11-14 03:24
Hi. I've tried the one you linked but I get an error when trying to `:source` it.. Yet setting `shellslash` still fixes the problem.

**Comment by weynhamz** [comment] 2012-11-20 01:17
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

The mechanism of checking buffers with duplicate name has been totally refactored(Thanks to @jmnas for the orginal work.), I believe that techlivezheng/vim-plugin-minibufexpl@5715dd9, techlivezheng/vim-plugin-minibufexpl@f3723aa, techlivezheng/vim-plugin-minibufexpl@950a81a and techlivezheng/vim-plugin-minibufexpl@763a623 should fix this issue now. Unique name generation has also been refactored, the string shown in MBE should uniquely identified the buffer now.

Please give it a try and let me know if it works.

**Comment by weynhamz** [comment] 2012-11-23 22:54
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.

**Closed as completed by weynhamz** 2012-11-23 22:54 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2013-05-10 18:08
Duplicate of #5
