### ISSUE TITLE
MBE stealing focus

### ISSUE THREAD

**Issue by acornejo** [fholgado/minibufexpl.vim#21] opened 2011-08-04 18:05 UTC
I've upgraded to this version of minibufexpl (mainly for the syntax highlighting of the buffer) and during regular usage I have stumbled across several bugs (I think they are all related, so I am only reporting one of them).

To reproduce:

First make open VIM and make sure your buffer list is empty. Open up NERDTree explorer and open two files, which should cause MBE to "activate" upon opening the second file. At this point, instead of the focus being on the second file, it will be on the MBE window. This causes havoc if you try to proceed with your edits without realizing you ended up in the wrong window.

I believe this bug is related to these ones:

https://github.com/fholgado/minibufexpl.vim/issues/3
https://github.com/fholgado/minibufexpl.vim/issues/7

It has to do with the way MBE handles focus. When opening the MBE window for the first time, it should give back focus to the correct window instead of stealing focus of the window.

**Comment by fholgado** [comment] 2012-02-27 03:24
This should be fixed in the latest build. Could you update and verify?

**Comment by AWinterman** [comment] 2012-06-26 18:30
I'm using the latest build, and this is happening with vim-ipython. I've set `let g:miniBufExplorerAutoUpdate= 0` to no avail.

**Comment by weynhamz** [comment] 2012-11-20 01:49
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

 I believe that techlivezheng/vim-plugin-minibufexpl@3add236 and techlivezheng/vim-plugin-minibufexpl@4155048 should fix this issue now. 

Please give it a try and let me know if it works.

**Comment by weynhamz** [comment] 2012-11-23 22:53
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.

**Closed as completed by weynhamz** 2012-11-23 22:53 UTC
Labels: bug, duplicate

**Comment by weynhamz** [comment] 2013-05-10 18:20
Duplicate of #3
