### ISSUE TITLE
Vim dies when doing wipeout on second buffer

### ISSUE THREAD

**Issue by ghost** [fholgado/minibufexpl.vim#95] opened 2013-07-07 21:16 UTC
I'm seeing an issue with `minibufexpl` where vim unexpectedly quits when I wipe out a buffer. I start up vim and load a file `:e foo.txt`, and then another one `:e bar.txt`. So now `minibufexpl` shows buffers `[1]` and `[2]`. So far so good. When I do a `:bwipeout`, I expect that `bar.txt` will be closed and I will be back at `foo.txt`. But when I have `minibufexpl` installed, this doesn't happen. Instead vim exits. Is this right? Is my vim `7.3.429` too old?

**Comment by weynhamz** [comment] 2013-07-08 02:53
Close as duplicate of #89.

**Closed as completed by weynhamz** 2013-07-08 02:53 UTC
Labels: bug, duplicate
