### ISSUE TITLE
a issue about code highlighting disappear weirdly

### ISSUE THREAD

**Issue by gtvforever** [fholgado/minibufexpl.vim#73] opened 2013-02-26 10:21 UTC
Hi Guys,

Recently, i installed minibufexpl on MacVim(OS X 10.8.2). I found a strange issue that the minibufexpl may cause the vim code highlighting does't work.

step 1, i open  source file  a.cpp,the code highlighting works fine;

step 2, i open another source file b.cpp, the minibufexpl starts to display buffer explorer;

step 3, i close one source file(a.cpp or b.cpp).In this case, i closed b.cpp then the minibuf explorer was disappeared.

step 4, when i look the only left file a.cpp, i found the code highlighting was disappeared. I have to input command :syntax on  to enable code highlighting.

I'm not sure it is a bug or not. So my question is how can i fix this issue? 

Thanks,
Guoming

**Comment by mvgrimes** [comment] 2013-02-26 19:47
Guoming,

I have had similar issues with syntax highlighting. I believe I was able to
fix the issue by moving the "syntax on" line to the bottom of my .vimrc
file, and adding checks to avoid reloading certain config files. For
example, I have this at the top of my .vim/ftplugin/perl.vim file:

```
if exists("b:did_perl_ftplugin") | finish | endif
let b:did_perl_ftplugin = 1
```

There is also a minibufexpl flag that you can set, which might help with
this (although I did not need to set it):

```
let g:miniBufExplForceSyntaxEnable = 1
```

Best of luck,
Mark

**Comment by gtvforever** [comment] 2013-02-27 10:38
Hi Mark,

Thank you for your quick reply. I've added  " let g:miniBufExplForceSyntaxEnable = 1" into my .vimrc profile. It seems that my previous issue have been resolved. 

However, i found another issue . The buf explorer highlighting feature would be disappeared if i set " let g:miniBufExplForceSyntaxEnable = 1" in the .vimrc profile. I think there may be some tricky codes cause this problem. Anyway, it's not a big problem for me.

Thank you very much again!

Best wishes,
Guoming

**Comment by weynhamz** [comment] 2013-05-08 10:06
Hey, please try the develop branch and let me know if it fixes your problem.

**Comment by weynhamz** [comment] 2013-05-11 04:06
Duplicate of #24

**Comment by weynhamz** [comment] 2013-05-11 06:06
Closing this issue, it should be fixed in the develop branch, feel free to reopen it.

**Closed as completed by weynhamz** 2013-05-11 06:06 UTC
Labels: bug, duplicate
